const tileData = [
  {
    id: 1,
    cover_img: require('./images/vanlife_snip.png'),
    title: 'Vanlife',
    description:
      "A van rental website that allows the user to browse though a list of vans, look up the details for each one and rent the van best suited for their needs and budget. Vanlife provides an interface for hosts that rent their vans and it requires authentication to access. In the host section the host is presented with insights on the income generated by their vans, reviews and also the ability to modify the information about the vans they have listed for rental. The application is built using React, React router, Firebase and it's responsive to all screens",
    repo_link: 'https://earnest-khapse-ab4478.netlify.app/',
  },
  {
    id: 2,
    cover_img: require('./images/airbnb_snip.png'),
    title: 'AirBnB experiences Clone',
    description:
      'AirBnB is a popular website for finding accomodation all over the world, experiences follows the same idea but for activities. This website is built with dynamic content, the experiences cards are not hard coded but are pulled from a database, they change on the availability or whether they are completed remotely or not.',
    repo_link: 'https://github.com/dario-berberi/airbbnb_clone',
  },
  {
    id: 3,
    cover_img: require('./images/search_match_snip.png'),
    title: 'Search and Match',
    description:
      'An application created to make searching for potential business partners fast and simple. The user needs to fill out a short form with the countries they are interested in operating and areas of shipping. Upon clicking "show results" they will be presented with the top 2 companies that best suit their requirements.',
    repo_link: 'https://github.com/dario-berberi/search-match-comp-area',
  },
];

export default tileData;
